-- =============================================================================
-- V1: Core domain — organizations, locations, departments, skills, users, employees
--
-- Conventions used throughout every migration in this project:
--   * UUID primary keys, generated by the application (not the database), so that
--     entities can be created and wired together before a transaction commits.
--   * Every tenant-scoped table carries organization_id, and every uniqueness rule is
--     scoped by it — two organizations must be able to use the same department name,
--     skill code or employee email without colliding.
--   * created_at / updated_at are timestamptz stored in UTC (see application.yml,
--     hibernate.jdbc.time_zone=UTC). Wall-clock scheduling values (dates, shift start/end)
--     are deliberately date/time WITHOUT timezone and interpreted in the location's own
--     zone — a shift that starts at 18:00 starts at 18:00 regardless of DST.
--   * version supports JPA optimistic locking so two managers cannot silently overwrite
--     each other (product brief §78).
-- =============================================================================

-- --- Organizations -----------------------------------------------------------
CREATE TABLE organizations (
    id          UUID PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    slug        VARCHAR(100) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_organizations_slug UNIQUE (slug),
    CONSTRAINT ck_organizations_name_not_blank CHECK (length(btrim(name)) > 0)
);

-- --- Locations ---------------------------------------------------------------
CREATE TABLE locations (
    id              UUID PRIMARY KEY,
    organization_id UUID         NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    name            VARCHAR(200) NOT NULL,
    -- IANA zone id, e.g. 'Europe/Berlin'. Every scheduling calculation for this location
    -- is done in this zone; DST transitions are explicitly handled, not assumed away.
    timezone        VARCHAR(64)  NOT NULL DEFAULT 'Europe/Berlin',
    address_line    VARCHAR(255),
    postal_code     VARCHAR(20),
    city            VARCHAR(120),
    country_code    CHAR(2),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_locations_org_name UNIQUE (organization_id, name),
    CONSTRAINT ck_locations_name_not_blank CHECK (length(btrim(name)) > 0)
);
CREATE INDEX ix_locations_organization ON locations (organization_id);

-- --- Departments -------------------------------------------------------------
-- Departments are data, never hardcoded enums: "Küche", "Theke", "Bar" for a restaurant,
-- "Backstube"/"Verkauf" for a bakery, whatever the operator needs.
CREATE TABLE departments (
    id              UUID PRIMARY KEY,
    organization_id UUID         NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    location_id     UUID         NOT NULL REFERENCES locations (id) ON DELETE CASCADE,
    name            VARCHAR(120) NOT NULL,
    description     VARCHAR(500),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_departments_location_name UNIQUE (location_id, name),
    CONSTRAINT ck_departments_name_not_blank CHECK (length(btrim(name)) > 0)
);
CREATE INDEX ix_departments_organization ON departments (organization_id);
CREATE INDEX ix_departments_location ON departments (location_id);

-- --- Skills ------------------------------------------------------------------
-- Skill catalogue per organization. Codes such as BAR, KITCHEN, CLOSING are seeded as
-- data (see the seed migration), not baked into the type system, so operators can add
-- their own (e.g. COCKTAIL_LEAD, HACCP_OFFICER) without a code change.
CREATE TABLE skills (
    id              UUID PRIMARY KEY,
    organization_id UUID         NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    code            VARCHAR(60)  NOT NULL,
    name            VARCHAR(120) NOT NULL,
    description     VARCHAR(500),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_skills_org_code UNIQUE (organization_id, code),
    CONSTRAINT ck_skills_code_format CHECK (code ~ '^[A-Z][A-Z0-9_]{1,59}$')
);
CREATE INDEX ix_skills_organization ON skills (organization_id);

-- --- Users -------------------------------------------------------------------
-- Login identity. Separate from `employees` on purpose: an org admin or an accountant may
-- need an account without being schedulable staff, and an employee record must survive
-- their login being deactivated.
CREATE TABLE users (
    id              UUID PRIMARY KEY,
    organization_id UUID         NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    email           VARCHAR(255) NOT NULL,
    -- bcrypt/delegating-encoder hash. A plaintext password is never stored or logged.
    password_hash   VARCHAR(255) NOT NULL,
    first_name      VARCHAR(120) NOT NULL,
    last_name       VARCHAR(120) NOT NULL,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version         BIGINT       NOT NULL DEFAULT 0,
    -- Email is unique globally (not per org) so that login by email alone is unambiguous.
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_email_format CHECK (position('@' in email) > 1)
);
CREATE INDEX ix_users_organization ON users (organization_id);

CREATE TABLE user_roles (
    user_id UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role    VARCHAR(40) NOT NULL,
    PRIMARY KEY (user_id, role),
    CONSTRAINT ck_user_roles_known CHECK (
        role IN ('EMPLOYEE', 'SHIFT_MANAGER', 'LOCATION_MANAGER', 'ORG_ADMIN', 'SUPER_ADMIN')
    )
);

-- --- Employees ---------------------------------------------------------------
CREATE TABLE employees (
    id                       UUID           PRIMARY KEY,
    organization_id          UUID           NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    -- Home location. Additional locations an employee may be scheduled at live in
    -- employee_locations; the solver treats scheduling outside those as a hard violation.
    location_id              UUID           NOT NULL REFERENCES locations (id) ON DELETE CASCADE,
    user_id                  UUID           REFERENCES users (id) ON DELETE SET NULL,
    first_name               VARCHAR(120)   NOT NULL,
    last_name                VARCHAR(120)   NOT NULL,
    email                    VARCHAR(255),
    employment_type          VARCHAR(30)    NOT NULL,
    hourly_wage              NUMERIC(10, 2) NOT NULL DEFAULT 0,
    contract_hours_per_week  NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    minimum_hours_per_week   NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    maximum_hours_per_week   NUMERIC(5, 2)  NOT NULL DEFAULT 48,
    active                   BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    version                  BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT uq_employees_user UNIQUE (user_id),
    CONSTRAINT ck_employees_employment_type CHECK (
        employment_type IN ('FULL_TIME', 'PART_TIME', 'MINIJOB', 'WORKING_STUDENT', 'TEMPORARY', 'OTHER')
    ),
    -- Labour-law limits are configuration, not constants baked into an employment type
    -- (product brief §8); these checks only enforce internal consistency.
    CONSTRAINT ck_employees_hours_range CHECK (
        minimum_hours_per_week >= 0
            AND maximum_hours_per_week >= minimum_hours_per_week
            AND contract_hours_per_week >= 0
    ),
    CONSTRAINT ck_employees_wage_non_negative CHECK (hourly_wage >= 0)
);
CREATE INDEX ix_employees_organization ON employees (organization_id);
CREATE INDEX ix_employees_location ON employees (location_id);
CREATE INDEX ix_employees_active ON employees (organization_id, active);

CREATE TABLE employee_skills (
    employee_id UUID NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
    skill_id    UUID NOT NULL REFERENCES skills (id) ON DELETE CASCADE,
    PRIMARY KEY (employee_id, skill_id)
);
CREATE INDEX ix_employee_skills_skill ON employee_skills (skill_id);

CREATE TABLE employee_departments (
    employee_id   UUID NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
    department_id UUID NOT NULL REFERENCES departments (id) ON DELETE CASCADE,
    PRIMARY KEY (employee_id, department_id)
);
CREATE INDEX ix_employee_departments_department ON employee_departments (department_id);

-- Locations an employee is cleared to work at (beyond their home location).
CREATE TABLE employee_locations (
    employee_id UUID NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
    location_id UUID NOT NULL REFERENCES locations (id) ON DELETE CASCADE,
    PRIMARY KEY (employee_id, location_id)
);
CREATE INDEX ix_employee_locations_location ON employee_locations (location_id);
